In [1]:
import sys

sys.path[0] = '/bbkinghome/mbarrera/git_supply/nndp/src'

import sys
import pandas as pd
import jax
import jax.numpy as jnp
import matplotlib.pyplot as plt
import optax
import nndp

from model import u, m, F, policy, T

key = jax.random.PRNGKey(0)
key, subkey = jax.random.split(key)
params, nn = nndp.initialize_deep_nn(subkey,
                                n_states = 3,
                                n_actions = 1,
                                nodes_per_layer = 128,
                                hidden_layers = 5,
                                hidden_activation = jax.nn.tanh,
                                output_activation = [jax.nn.sigmoid])

In [32]:
state = jnp.array([[0,1,1],[0,1,2]])
action = policy(state, params, nn)

action = jnp.array([[0.4],[0.5]])

In [33]:
u(state,action)

Array([-10.959582, -10.717734], dtype=float32)

In [39]:
jax.jacrev(lambda action: u(state, action))(action)

Array([[[2.7398956],
        [0.       ]],

       [[0.       ],
        [2.143547 ]]], dtype=float32)

In [46]:
jax.vmap(jax.grad(lambda action, state: u(state, action)))(action, state)

Array([[2.7398956],
       [2.143547 ]], dtype=float32)

In [40]:
jax.jacrev(lambda action: jnp.sum(u(state, action), axis=0))(action)


Array([[2.7398956],
       [2.143547 ]], dtype=float32)